### ISSUE TITLE
Generic instance for Foreign

### ISSUE THREAD

**Issue by texastoland** [paf31/purescript-foreign-generic#12]
Would this be conceivable essentially serializing and deserializing JSON around a data constructor?

**Comment by paf31** [comment]
It might be possible to come up with a newtype around `Foreign`, give it a fake `Generic` instance, and match its type constructor name explictly. It would be a complete hack of course 😄 

I doubt we'd want to provide a `Foreign` constructor in `GenericSignature`, since that would need the compiler to know about the `Foreign` library.

**Comment by texastoland** [comment]
> It might be possible to come up with a newtype around `Foreign`,

Why not around `Foreign` itself? I'm trying to write the instance right now.

**Comment by paf31** [comment]
No generic instance.

**Comment by texastoland** [comment]
In retrospect I have the same issue with `Date`. I guess I should be using something like `argonaut` and just defer to the `Generic` instances available instead of trying to do everything that way.
